package buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes the identity vocabulary of platform.yml (ADR-0003, ADR-0030) into `META-INF/platform/identity.properties`
 * under [outputDir], a resource directory of the module. The apps' `ConnectorIdentity` reads it at start-up, so the
 * vocabulary is declared once and the running app checks its identity against the same lists as the deploy tools.
 */
@CacheableTask
abstract class PlatformIdentityTask : DefaultTask() {
    @get:Input
    abstract val regions: ListProperty<String>

    @get:Input
    abstract val stages: ListProperty<String>

    @get:Input
    abstract val flows: ListProperty<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun write() {
        val file = outputDir.get().asFile.resolve(RESOURCE)
        file.parentFile.mkdirs()
        // Fixed order, no timestamp: the resource, and so the jar, stays reproducible.
        file.writeText(
            "# The identity vocabulary of platform.yml (ADR-0003, ADR-0030), generated by the build: do not edit.\n" +
                "regions=${regions.get().joinToString(",")}\n" +
                "stages=${stages.get().joinToString(",")}\n" +
                "flows=${flows.get().joinToString(",")}\n",
        )
    }

    companion object {
        const val RESOURCE = "META-INF/platform/identity.properties"
    }
}
