package buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes the values of platform.yml that the running app reads into `META-INF/platform/identity.properties` under
 * [outputDir], a resource directory of the module: the identity vocabulary (ADR-0003, ADR-0030), which
 * `ConnectorIdentity` checks at start-up, and the apps' own property roots and secret properties (ADR-0042), which
 * `ConfigurationSummary` shows and `SecretMasker` masks. Each value is declared once, and the running app reads the
 * same lists as the deploy tools and config-lint.
 */
@CacheableTask
abstract class PlatformIdentityTask : DefaultTask() {
    @get:Input
    abstract val regions: ListProperty<String>

    @get:Input
    abstract val stages: ListProperty<String>

    @get:Input
    abstract val flows: ListProperty<String>

    /** platform.yml `property_prefixes` (ADR-0042). */
    @get:Input
    abstract val propertyPrefixes: ListProperty<String>

    /** platform.yml `secret_properties` (ADR-0042); may be empty. */
    @get:Input
    abstract val secretProperties: ListProperty<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun write() {
        val file = outputDir.get().asFile.resolve(RESOURCE)
        file.parentFile.mkdirs()
        // Fixed order, no timestamp: the resource, and so the jar, stays reproducible.
        file.writeText(
            "# The values of platform.yml that the running app reads (ADR-0030, ADR-0042), generated by the build: " +
                "do not edit.\n" +
                "regions=${regions.get().joinToString(",")}\n" +
                "stages=${stages.get().joinToString(",")}\n" +
                "flows=${flows.get().joinToString(",")}\n" +
                "property_prefixes=${propertyPrefixes.get().joinToString(",")}\n" +
                "secret_properties=${secretProperties.get().joinToString(",")}\n",
        )
    }

    companion object {
        const val RESOURCE = "META-INF/platform/identity.properties"
    }
}
