# Layer 4 — trades from SQL Server towards AMPS; the stub sink stands in for AMPS until it is licensed.
connector:
  source:
    database: trades
    table: dbo.trades
  sink:
    type: stub
    amps:
      topic: cash.trades
