# Layer 3 — source-amps on a laptop / in CI test stacks. AMPS is licensed and not in the demo stack:
# the source endpoint names the service a licensed stack would provide.
connector:
  source:
    host: amps
    port: 9007
    poll-interval: 1s
  sink:
    deephaven:
      host: deephaven
      port: 10000
